# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/XDC.xdc

# IP: ip/MULTI_Voltage2temp/MULTI_Voltage2temp.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MULTI_Voltage2temp || ORIG_REF_NAME==MULTI_Voltage2temp} -quiet] -quiet
