# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.cache/wt [current_project]
set_property parent.project_path C:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/src/Contorl.v
  C:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/src/DAC/DAC_5676.v
  C:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/src/Uart/Uart_Output.v
  C:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/src/Voltage2Temp.v
  C:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/src/ADC/ad7606.v
  C:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/src/Uart/uart_sub/uart_rx.v
  C:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/src/Uart/uart_sub/uart_sub.v
  C:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/src/Uart/uart_top.v
  C:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/src/Uart/uart_sub/uart_tx.v
  C:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/src/ADC/volt_cal.v
  C:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/src/Multi_Channel_top.v
  C:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/src/Pid.v
  C:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/src/test.v
}
read_ip -quiet C:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/ip/MULTI_Voltage2temp/MULTI_Voltage2temp.xci
set_property used_in_implementation false [get_files -all c:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/ip/MULTI_Voltage2temp/MULTI_Voltage2temp_ooc.xdc]

read_ip -quiet C:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/ip/DAC_fifo/DAC_fifo.xci
set_property used_in_implementation false [get_files -all c:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/ip/DAC_fifo/DAC_fifo.xdc]
set_property used_in_implementation false [get_files -all c:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/ip/DAC_fifo/DAC_fifo_ooc.xdc]

read_ip -quiet C:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/ip/uart_send_fifo/uart_send_fifo.xci
set_property used_in_implementation false [get_files -all c:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/ip/uart_send_fifo/uart_send_fifo.xdc]
set_property used_in_implementation false [get_files -all c:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/ip/uart_send_fifo/uart_send_fifo_ooc.xdc]

read_ip -quiet C:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/ip/Mul_PID/Mul_PID.xci
set_property used_in_implementation false [get_files -all c:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/ip/Mul_PID/Mul_PID_ooc.xdc]

read_ip -quiet C:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/ip/Mul_P/Mul_P.xci
set_property used_in_implementation false [get_files -all c:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/ip/Mul_P/Mul_P_ooc.xdc]

read_ip -quiet C:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/ip/PID_adder/PID_adder.xci
set_property used_in_implementation false [get_files -all c:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/ip/PID_adder/PID_adder_ooc.xdc]

read_ip -quiet C:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/ip/PID_SUB/PID_SUB.xci
set_property used_in_implementation false [get_files -all c:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/sources_1/ip/PID_SUB/PID_SUB_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/constrs_1/new/XDC.xdc
set_property used_in_implementation false [get_files C:/Users/quanzai/Desktop/xidian_4channel-master/xidian_4channel-master/xdu_4channel/xdu_4channel.srcs/constrs_1/new/XDC.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Multi_Channel_top -part xc7a35tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Multi_Channel_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Multi_Channel_top_utilization_synth.rpt -pb Multi_Channel_top_utilization_synth.pb"
