# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/quanzai/Desktop/xidian_4channel/xdu_4channel/xdu_4channel.srcs/sources_1/ip/Mul_P/Mul_P.xci
# IP: The module: 'Mul_P' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/quanzai/Desktop/xidian_4channel/xdu_4channel/xdu_4channel.srcs/sources_1/ip/Mul_P/Mul_P_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mul_P'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/quanzai/Desktop/xidian_4channel/xdu_4channel/xdu_4channel.srcs/sources_1/ip/Mul_P/Mul_P.xci
# IP: The module: 'Mul_P' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/quanzai/Desktop/xidian_4channel/xdu_4channel/xdu_4channel.srcs/sources_1/ip/Mul_P/Mul_P_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mul_P'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
