set_property PACKAGE_PIN Y18 [get_ports clk]
set_property PACKAGE_PIN A18 [get_ports DAC1_RST]
set_property PACKAGE_PIN W22 [get_ports DAC2_RST]
set_property PACKAGE_PIN P15 [get_ports rst_n]
set_property PACKAGE_PIN D19 [get_ports {AD_data_1[0]}]
set_property PACKAGE_PIN E19 [get_ports {AD_data_1[1]}]
set_property PACKAGE_PIN F20 [get_ports {AD_data_1[2]}]
set_property PACKAGE_PIN F19 [get_ports {AD_data_1[3]}]
set_property PACKAGE_PIN E18 [get_ports {AD_data_1[4]}]
set_property PACKAGE_PIN F18 [get_ports {AD_data_1[5]}]
set_property PACKAGE_PIN C17 [get_ports {AD_data_1[6]}]
set_property PACKAGE_PIN D17 [get_ports {AD_data_1[7]}]
set_property PACKAGE_PIN E17 [get_ports {AD_data_1[8]}]
set_property PACKAGE_PIN F16 [get_ports {AD_data_1[9]}]
set_property PACKAGE_PIN E16 [get_ports {AD_data_1[10]}]
set_property PACKAGE_PIN D16 [get_ports {AD_data_1[11]}]
set_property PACKAGE_PIN E14 [get_ports {AD_data_1[12]}]
set_property PACKAGE_PIN E13 [get_ports {AD_data_1[13]}]
set_property PACKAGE_PIN F14 [get_ports {AD_data_1[14]}]
set_property PACKAGE_PIN F13 [get_ports {AD_data_1[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports DAC1_RST]
set_property IOSTANDARD LVCMOS33 [get_ports DAC2_RST]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN A21 [get_ports {AD_os_1[0]}]
set_property PACKAGE_PIN B21 [get_ports {AD_os_1[1]}]
set_property PACKAGE_PIN B22 [get_ports {AD_os_1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_os_1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_os_1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_os_1[0]}]
set_property PACKAGE_PIN G22 [get_ports AD_busy_1]

set_property PACKAGE_PIN D22 [get_ports AD_convstab_1B]
set_property PACKAGE_PIN E21 [get_ports AD_cs_1]
set_property PACKAGE_PIN G21 [get_ports AD_first_data_1]
set_property PACKAGE_PIN D21 [get_ports AD_rd_1]
set_property PACKAGE_PIN E22 [get_ports AD_reset_1]
set_property PACKAGE_PIN A19 [get_ports DAC1_CS]
set_property PACKAGE_PIN B17 [get_ports DAC1_LDAC]
set_property PACKAGE_PIN B18 [get_ports DAC1_MISO]
set_property PACKAGE_PIN B20 [get_ports DAC1_MOSI]
set_property PACKAGE_PIN A20 [get_ports DAC1_SCLK]
set_property PACKAGE_PIN AB22 [get_ports DAC2_CS]
set_property PACKAGE_PIN U22 [get_ports DAC2_LDAC]
set_property PACKAGE_PIN V22 [get_ports DAC2_MISO]
set_property PACKAGE_PIN AA20 [get_ports DAC2_MOSI]
set_property PACKAGE_PIN AA21 [get_ports DAC2_SCLK]
set_property PACKAGE_PIN R1 [get_ports rx]
set_property PACKAGE_PIN P1 [get_ports tx]
set_property IOSTANDARD LVCMOS33 [get_ports AD_busy_1]
set_property IOSTANDARD LVCMOS33 [get_ports AD_convstab_1A]
set_property IOSTANDARD LVCMOS33 [get_ports AD_convstab_1B]
set_property IOSTANDARD LVCMOS33 [get_ports AD_cs_1]
set_property IOSTANDARD LVCMOS33 [get_ports AD_first_data_1]
set_property IOSTANDARD LVCMOS33 [get_ports AD_rd_1]
set_property IOSTANDARD LVCMOS33 [get_ports AD_reset_1]
set_property IOSTANDARD LVCMOS33 [get_ports DAC1_CS]
set_property IOSTANDARD LVCMOS33 [get_ports DAC1_LDAC]
set_property IOSTANDARD LVCMOS33 [get_ports DAC1_MISO]
set_property IOSTANDARD LVCMOS33 [get_ports DAC1_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports DAC1_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports DAC2_CS]
set_property IOSTANDARD LVCMOS33 [get_ports DAC2_LDAC]
set_property IOSTANDARD LVCMOS33 [get_ports DAC2_MISO]
set_property IOSTANDARD LVCMOS33 [get_ports DAC2_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports DAC2_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports tx]

set_property PACKAGE_PIN D22 [get_ports AD_convstab_1]
set_property IOSTANDARD LVCMOS33 [get_ports AD_convstab_1]







connect_debug_port u_ila_0/probe0 [get_nets [list {u_pid_contorl/AD_output[0]} {u_pid_contorl/AD_output[1]} {u_pid_contorl/AD_output[2]} {u_pid_contorl/AD_output[3]} {u_pid_contorl/AD_output[4]} {u_pid_contorl/AD_output[5]} {u_pid_contorl/AD_output[6]} {u_pid_contorl/AD_output[7]} {u_pid_contorl/AD_output[8]} {u_pid_contorl/AD_output[9]} {u_pid_contorl/AD_output[10]} {u_pid_contorl/AD_output[11]} {u_pid_contorl/AD_output[12]} {u_pid_contorl/AD_output[13]} {u_pid_contorl/AD_output[14]} {u_pid_contorl/AD_output[15]}]]



connect_debug_port u_ila_0/probe3 [get_nets [list {target_temp[0]} {target_temp[1]} {target_temp[2]} {target_temp[3]} {target_temp[4]} {target_temp[5]} {target_temp[6]} {target_temp[7]} {target_temp[8]} {target_temp[9]} {target_temp[10]} {target_temp[11]} {target_temp[12]} {target_temp[13]} {target_temp[14]} {target_temp[15]}]]





create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {u_pid_contorl/P[0]} {u_pid_contorl/P[1]} {u_pid_contorl/P[2]} {u_pid_contorl/P[3]} {u_pid_contorl/P[4]} {u_pid_contorl/P[5]} {u_pid_contorl/P[6]} {u_pid_contorl/P[7]} {u_pid_contorl/P[8]} {u_pid_contorl/P[9]} {u_pid_contorl/P[10]} {u_pid_contorl/P[11]} {u_pid_contorl/P[12]} {u_pid_contorl/P[13]} {u_pid_contorl/P[14]} {u_pid_contorl/P[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {u_pid_contorl/I[0]} {u_pid_contorl/I[1]} {u_pid_contorl/I[2]} {u_pid_contorl/I[3]} {u_pid_contorl/I[4]} {u_pid_contorl/I[5]} {u_pid_contorl/I[6]} {u_pid_contorl/I[7]} {u_pid_contorl/I[8]} {u_pid_contorl/I[9]} {u_pid_contorl/I[10]} {u_pid_contorl/I[11]} {u_pid_contorl/I[12]} {u_pid_contorl/I[13]} {u_pid_contorl/I[14]} {u_pid_contorl/I[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {u_pid_contorl/error_sum_1[0]} {u_pid_contorl/error_sum_1[1]} {u_pid_contorl/error_sum_1[2]} {u_pid_contorl/error_sum_1[3]} {u_pid_contorl/error_sum_1[4]} {u_pid_contorl/error_sum_1[5]} {u_pid_contorl/error_sum_1[6]} {u_pid_contorl/error_sum_1[7]} {u_pid_contorl/error_sum_1[8]} {u_pid_contorl/error_sum_1[9]} {u_pid_contorl/error_sum_1[10]} {u_pid_contorl/error_sum_1[11]} {u_pid_contorl/error_sum_1[12]} {u_pid_contorl/error_sum_1[13]} {u_pid_contorl/error_sum_1[14]} {u_pid_contorl/error_sum_1[15]} {u_pid_contorl/error_sum_1[16]} {u_pid_contorl/error_sum_1[17]} {u_pid_contorl/error_sum_1[18]} {u_pid_contorl/error_sum_1[19]} {u_pid_contorl/error_sum_1[20]} {u_pid_contorl/error_sum_1[21]} {u_pid_contorl/error_sum_1[22]} {u_pid_contorl/error_sum_1[23]} {u_pid_contorl/error_sum_1[24]} {u_pid_contorl/error_sum_1[25]} {u_pid_contorl/error_sum_1[26]} {u_pid_contorl/error_sum_1[27]} {u_pid_contorl/error_sum_1[28]} {u_pid_contorl/error_sum_1[29]} {u_pid_contorl/error_sum_1[30]} {u_pid_contorl/error_sum_1[31]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
