set_property PACKAGE_PIN Y18 [get_ports clk]
set_property PACKAGE_PIN A18 [get_ports DAC1_RST]
set_property PACKAGE_PIN W22 [get_ports DAC2_RST]
set_property PACKAGE_PIN P15 [get_ports rst_n]
set_property PACKAGE_PIN D19 [get_ports {AD_data_1[0]}]
set_property PACKAGE_PIN E19 [get_ports {AD_data_1[1]}]
set_property PACKAGE_PIN F20 [get_ports {AD_data_1[2]}]
set_property PACKAGE_PIN F19 [get_ports {AD_data_1[3]}]
set_property PACKAGE_PIN E18 [get_ports {AD_data_1[4]}]
set_property PACKAGE_PIN F18 [get_ports {AD_data_1[5]}]
set_property PACKAGE_PIN C17 [get_ports {AD_data_1[6]}]
set_property PACKAGE_PIN D17 [get_ports {AD_data_1[7]}]
set_property PACKAGE_PIN E17 [get_ports {AD_data_1[8]}]
set_property PACKAGE_PIN F16 [get_ports {AD_data_1[9]}]
set_property PACKAGE_PIN E16 [get_ports {AD_data_1[10]}]
set_property PACKAGE_PIN D16 [get_ports {AD_data_1[11]}]
set_property PACKAGE_PIN E14 [get_ports {AD_data_1[12]}]
set_property PACKAGE_PIN E13 [get_ports {AD_data_1[13]}]
set_property PACKAGE_PIN F14 [get_ports {AD_data_1[14]}]
set_property PACKAGE_PIN F13 [get_ports {AD_data_1[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data_1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports DAC1_RST]
set_property IOSTANDARD LVCMOS33 [get_ports DAC2_RST]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN A21 [get_ports {AD_os_1[0]}]
set_property PACKAGE_PIN B21 [get_ports {AD_os_1[1]}]
set_property PACKAGE_PIN B22 [get_ports {AD_os_1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_os_1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_os_1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_os_1[0]}]
set_property PACKAGE_PIN G22 [get_ports AD_busy_1]

set_property PACKAGE_PIN D22 [get_ports AD_convstab_1B]
set_property PACKAGE_PIN E21 [get_ports AD_cs_1]
set_property PACKAGE_PIN G21 [get_ports AD_first_data_1]
set_property PACKAGE_PIN D21 [get_ports AD_rd_1]
set_property PACKAGE_PIN E22 [get_ports AD_reset_1]
set_property PACKAGE_PIN A19 [get_ports DAC1_CS]
set_property PACKAGE_PIN B17 [get_ports DAC1_LDAC]
set_property PACKAGE_PIN B18 [get_ports DAC1_MISO]
set_property PACKAGE_PIN B20 [get_ports DAC1_MOSI]
set_property PACKAGE_PIN A20 [get_ports DAC1_SCLK]
set_property PACKAGE_PIN AB22 [get_ports DAC2_CS]
set_property PACKAGE_PIN U22 [get_ports DAC2_LDAC]
set_property PACKAGE_PIN V22 [get_ports DAC2_MISO]
set_property PACKAGE_PIN AA20 [get_ports DAC2_MOSI]
set_property PACKAGE_PIN AA21 [get_ports DAC2_SCLK]
set_property PACKAGE_PIN R1 [get_ports rx]
set_property PACKAGE_PIN P1 [get_ports tx]
set_property IOSTANDARD LVCMOS33 [get_ports AD_busy_1]
set_property IOSTANDARD LVCMOS33 [get_ports AD_convstab_1A]
set_property IOSTANDARD LVCMOS33 [get_ports AD_convstab_1B]
set_property IOSTANDARD LVCMOS33 [get_ports AD_cs_1]
set_property IOSTANDARD LVCMOS33 [get_ports AD_first_data_1]
set_property IOSTANDARD LVCMOS33 [get_ports AD_rd_1]
set_property IOSTANDARD LVCMOS33 [get_ports AD_reset_1]
set_property IOSTANDARD LVCMOS33 [get_ports DAC1_CS]
set_property IOSTANDARD LVCMOS33 [get_ports DAC1_LDAC]
set_property IOSTANDARD LVCMOS33 [get_ports DAC1_MISO]
set_property IOSTANDARD LVCMOS33 [get_ports DAC1_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports DAC1_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports DAC2_CS]
set_property IOSTANDARD LVCMOS33 [get_ports DAC2_LDAC]
set_property IOSTANDARD LVCMOS33 [get_ports DAC2_MISO]
set_property IOSTANDARD LVCMOS33 [get_ports DAC2_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports DAC2_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports tx]

set_property PACKAGE_PIN D22 [get_ports AD_convstab_1]
set_property IOSTANDARD LVCMOS33 [get_ports AD_convstab_1]







connect_debug_port u_ila_0/probe0 [get_nets [list {u_pid_contorl/AD_output[0]} {u_pid_contorl/AD_output[1]} {u_pid_contorl/AD_output[2]} {u_pid_contorl/AD_output[3]} {u_pid_contorl/AD_output[4]} {u_pid_contorl/AD_output[5]} {u_pid_contorl/AD_output[6]} {u_pid_contorl/AD_output[7]} {u_pid_contorl/AD_output[8]} {u_pid_contorl/AD_output[9]} {u_pid_contorl/AD_output[10]} {u_pid_contorl/AD_output[11]} {u_pid_contorl/AD_output[12]} {u_pid_contorl/AD_output[13]} {u_pid_contorl/AD_output[14]} {u_pid_contorl/AD_output[15]}]]



connect_debug_port u_ila_0/probe3 [get_nets [list {target_temp[0]} {target_temp[1]} {target_temp[2]} {target_temp[3]} {target_temp[4]} {target_temp[5]} {target_temp[6]} {target_temp[7]} {target_temp[8]} {target_temp[9]} {target_temp[10]} {target_temp[11]} {target_temp[12]} {target_temp[13]} {target_temp[14]} {target_temp[15]}]]








