# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Administrator/Desktop/xidian_4channel/xdu_4channel/xdu_4channel.srcs/sources_1/ip/Mul_PID/Mul_PID.xci
# IP: The module: 'Mul_PID' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Desktop/xidian_4channel/xdu_4channel/xdu_4channel.srcs/sources_1/ip/Mul_PID/Mul_PID_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mul_PID'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Administrator/Desktop/xidian_4channel/xdu_4channel/xdu_4channel.srcs/sources_1/ip/Mul_PID/Mul_PID.xci
# IP: The module: 'Mul_PID' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Desktop/xidian_4channel/xdu_4channel/xdu_4channel.srcs/sources_1/ip/Mul_PID/Mul_PID_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mul_PID'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
