# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/quanzai/Desktop/xidian_4channel/xdu_4channel/xdu_4channel.srcs/sources_1/ip/PID_SUB/PID_SUB.xci
# IP: The module: 'PID_SUB' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/quanzai/Desktop/xidian_4channel/xdu_4channel/xdu_4channel.srcs/sources_1/ip/PID_SUB/PID_SUB_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PID_SUB'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/quanzai/Desktop/xidian_4channel/xdu_4channel/xdu_4channel.srcs/sources_1/ip/PID_SUB/PID_SUB.xci
# IP: The module: 'PID_SUB' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/quanzai/Desktop/xidian_4channel/xdu_4channel/xdu_4channel.srcs/sources_1/ip/PID_SUB/PID_SUB_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PID_SUB'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
