# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/quanzai/Desktop/xidian_4channel/xdu_4channel/xdu_4channel.srcs/sources_1/ip/DAC_fifo/DAC_fifo.xci
# IP: The module: 'DAC_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/quanzai/Desktop/xidian_4channel/xdu_4channel/xdu_4channel.srcs/sources_1/ip/DAC_fifo/DAC_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'DAC_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/quanzai/Desktop/xidian_4channel/xdu_4channel/xdu_4channel.srcs/sources_1/ip/DAC_fifo/DAC_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DAC_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/quanzai/Desktop/xidian_4channel/xdu_4channel/xdu_4channel.srcs/sources_1/ip/DAC_fifo/DAC_fifo.xci
# IP: The module: 'DAC_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/quanzai/Desktop/xidian_4channel/xdu_4channel/xdu_4channel.srcs/sources_1/ip/DAC_fifo/DAC_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'DAC_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/quanzai/Desktop/xidian_4channel/xdu_4channel/xdu_4channel.srcs/sources_1/ip/DAC_fifo/DAC_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DAC_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
